package:
  name: uid_wrapper
  version: 1.3.2
  epoch: 0
  description: A wrapper for the user, group and hosts NSS API
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - cmocka-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.samba.org/uid_wrapper.git
      tag: uid_wrapper-${{package.version}}
      expected-commit: 1e574af87d4cc6d072974d34def808ab7b726c4f

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_INSTALL_PREFIX=/usr
        -DCMAKE_BUILD_TYPE=Release
        -DUNIT_TESTING=ON
        -DCMAKE_C_FLAGS="-O2 -include stdint.h"

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    description: ${{package.name}} dev
    test:
      pipeline:
        - uses: test/pkgconf

  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
    description: ${{package.name}} manpages
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/tw/ldd-check

update:
  enabled: true
  git:
    strip-prefix: uid_wrapper-
    tag-filter-prefix: uid_wrapper-
